# Generated by Django 5.2 on 2025-04-25 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rfid_code', models.CharField(max_length=255, unique=True)),
                ('fingerprint_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('rfid_code', models.CharField(blank=True, max_length=255, null=True)),
                ('fingerprint_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='box.user')),
            ],
        ),
        migrations.CreateModel(
            name='DosageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dosage', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_schedules', to='box.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
