# Generated by Django 5.2 on 2025-04-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosageschedule',
            options={'verbose_name': 'برنامه مصرف دارو', 'verbose_name_plural': 'برنامه\u200cهای مصرف دارو'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': 'گزارش رویداد', 'verbose_name_plural': 'گزارش\u200cهای رویداد'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='dosageschedule',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dosageschedule',
            name='dosage',
            field=models.FloatField(verbose_name='مقدار مصرف'),
        ),
        migrations.AlterField(
            model_name='dosageschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_schedules', to='box.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان رویداد'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(max_length=50, verbose_name='نوع رویداد'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه اثر انگشت'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد RFID'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='box.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fingerprint_id',
            field=models.IntegerField(unique=True, verbose_name='شناسه اثر انگشت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfid_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='کد RFID'),
        ),
    ]
