# Generated by Django 5.2 on 2025-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_dosageschedule_options_alter_eventlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageschedule',
            name='used',
            field=models.BooleanField(default=False, verbose_name='وضعیت مصرف'),
        ),
    ]
