# Generated by Django 5.2 on 2025-07-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_dosageschedule_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageschedule',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ'),
        ),
    ]
