# Generated by Django 5.2 on 2025-07-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_alter_dosageschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageschedule',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
